############# 中文导航 ##############

# 主菜单

[[main]]
name = "首页"
url = ""
weight = 1

[[main]]
name = "关于我们"
url = "about/"
weight = 2

[[main]]
name = "产品"
url = "project/"
weight = 3

[[main]]
name = "新闻"
url = "blog/"
weight = 4

[[main]]
weight = 5
name = "更多"
hasChildren = true

  [[main]]
  parent = "更多"
  name = "服务"
  url = "service/"
  weight = 1

  [[main]]
  parent = "更多"
  name = "价格"
  url = "pricing/"
  weight = 2

  [[main]]
  parent = "更多"
  name = "常见问题"
  url = "faq/"
  weight = 3

[[main]]
name = "联系方式"
url = "contact/"
weight = 6

# 页脚菜单

[[footer]]
name = "关于"
url = "about/"
weight = 2

[[footer]]
name = "项目"
url = "project/"
weight = 3

[[footer]]
name = "服务"
url = "service/"
weight = 4

[[footer]]
name = "价格"
url = "pricing/"
weight = 5

[[footer]]
name = "常见问题"
url = "faq/"
weight = 6

[[footer]]
name = "联系方式"
url = "contact/"
weight = 7