############# 中文导航 ##############

# 主菜单

[[main]]
name = "首页"
url = ""
weight = 1

[[main]]
name = "公司概况"
url = "about/"
weight = 2

[[main]]
name = "产品中心"
url = "project/product1"
weight = 3

[[main]]
name = "公司动态"
url = "blog/"
weight = 4

[[main]]
name = "联系我们"
url = "contact/"
weight = 6

# 页脚菜单

[[footer]]
name = "关于"
url = "about/"
weight = 2

[[footer]]
name = "项目"
url = "project/"
weight = 3

[[footer]]
name = "服务"
url = "service/"
weight = 4

[[footer]]
name = "价格"
url = "pricing/"
weight = 5

[[footer]]
name = "常见问题"
url = "faq/"
weight = 6

[[footer]]
name = "联系我们"
url = "contact/"
weight = 7